baseurl = "https://asoldatenko.org/"
languageCode = "en-us"
title = "Personal Blog"

theme = "lanyon-hugo"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
pygmentsuseclasses = true

googleAnalytics = "UA-76003429-1"
disqusShortname = "https-golangfortwo-com"

[permalinks]
post = ":year/:month/:day/:title/"
fixed = ":title/"

[markup.goldmark.extensions]
typographer = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "categories"
name = "Categories Section from Menu"
title = "Categories section"
url = "/categories/"
weight = -110

[params]
Title = "Andrii's blog"
Tagline = "Blog about programming"
Description = "A blog about tips and tricks in the differen programming languages over a cup of coffee ☕"
Author = "Andrii Soldatenko"
mainSections = [ "post" ]
disableFonts = false

