title = "Personal Blog"
baseurl = "https://asoldatenko.org/"

# This is what goes in <html lang="">
languageCode = "en-us"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.
ignoreLogs = ['additional-script-loading-error']

# modern way: pull in theme component as hugo module
[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"


[services]
  # To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
  # To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = 'UA-76003429-1' # G-MEASUREMENT_ID

  # To enable Disqus comments, provide Disqus Shortname below.
  # To disable Disqus comments, simply leave the field empty or remove the next two lines
  #  [services.disqus]
  #    shortname = 'asoldatenko-org'

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
    [markup.tableOfContents]
      startLevel = 2 # ToC starts from H2
      endLevel = 4 # ToC ends at H4
      ordered = true # generates <ul> instead of <ol>


############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

[Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="talks"
    name = 'Talks'
    url = '/talks/'
    weight = 30
  [[Languages.en-gb.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 40
  [[Languages.en-gb.menu.main]]
    pageRef="notes"
    name = 'Notes'
    url = '/notes/'
    weight = 50

[Languages.en-gb.params]
  sitename = "andrii soldatenko blog about programming"
  defaultColor = "light" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Andrii's blog about programming, hacking and other random stuff."
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button

  # additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).

  # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  dateFormat = "02 Jan 2006"
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog posts in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog posts in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-gb.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Andrii's blog about programming"
  name = "Andrii Soldatenko"
  description = "hacking and tips and tricks i learnt over a cup of coffee ☕"

# Allow overriding webmanifest options
[Languages.en-gb.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  # background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"


# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/andriisoldatenko"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/a_soldatenko"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[outputs]
home = ['html', 'rss', 'json']
page = ['html']